name: Skillsaw3
version: '1.16.0'
api-version: 1.14
author: Pangamma
#website: CustomPlugin
main: com.lumengaming.skillsaw.SpigotMain
description: Custom build skill rank system.
commands:
  pvpmode:
    description: 'Enable or disable PVP mode.'
    aliases: ['pvpm']
  test2:
    description: 'Test'
  title:
    description: 'A placeholder so we do not get command suggestions for the vanilla command'
  tp:
    description: 'A placeholder so we do not get command suggestions for the vanilla command'
#  testlock:
#    description: 'Lock the main thread.'
#  setskill:
#    description: 'for moderators only. Allows you to set the skill level for a user.'
#    aliases: ['skillset','ss']
#  title:
#    description: 'set in game group name.'
#    aliases: ['title']
#  rep-natural:
#    description: 'natural rep'
#    aliases: ['rep-nat','rep','rep-n',nrep,rep-natural]
#  rep-fix:
#    description: 'for fixing rep or disciplinary action.'
#    aliases: ['xrep','repx']
#  rep-staff:
#    description: 'staff rep'
#    aliases: ['rep-s','s-rep','srep']
#  rep-note:
#    description: 'View notes on users.'
#    aliases: ['note']
#  nickname:
#    aliases: ['nick']
#  review:
#    aliases: ['rev','revew']
#  congratulate:
#    description: 'help'
#    aliases: ['grats','congrats','praise','congratulations']
#  scold:
#    aliases: ['unpraise','boo']
#  channel:
#    aliases: ['ch']
#  mee:
#    aliases: ['me']
#  mute:
#    aliases: ['softmute','smute']
#  unmute:
#    description: 'Undo a mute'
#  ignore:
#    description: 'Ignore up to 10 players'
#  global:
#    description: 'Chat on the global channel.'
#    aliases: ['g']
#  chatcolor:
#    description: 'Changes your default chat color.'
#  replog:
#    description: 'View logs for a player. Rep logs.'
#    aliases: ['sreplog','xreplog','notes','viewlog','vlog']
#  staff:
#    description: 'find staff, manage staff membership'
#    aliases: ['staff','setstaff','staffset']
#  instructor:
#    description: 'find staff, manage staff membership'
#    aliases: ['instructors','instr','instruct','inst']